// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqip6Jq2lugr1KvkBQMvA1enCffUNwH-E',
    appId: '1:346868082875:web:502fac14c68d4ba8c7e19e',
    messagingSenderId: '346868082875',
    projectId: 'mhealth-6191e',
    authDomain: 'mhealth-6191e.firebaseapp.com',
    databaseURL: 'https://mhealth-6191e-default-rtdb.firebaseio.com',
    storageBucket: 'mhealth-6191e.appspot.com',
    measurementId: 'G-75BPJD6QVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUt_W7sme9H31aO3dLzqI1aNSeQVMClEo',
    appId: '1:346868082875:android:189ed9cb28aca144c7e19e',
    messagingSenderId: '346868082875',
    projectId: 'mhealth-6191e',
    databaseURL: 'https://mhealth-6191e-default-rtdb.firebaseio.com',
    storageBucket: 'mhealth-6191e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfzHKLMBA3XEvGztkt40Jn7tT4fPJeKpU',
    appId: '1:346868082875:ios:984e0bf81db5283fc7e19e',
    messagingSenderId: '346868082875',
    projectId: 'mhealth-6191e',
    databaseURL: 'https://mhealth-6191e-default-rtdb.firebaseio.com',
    storageBucket: 'mhealth-6191e.appspot.com',
    androidClientId: '346868082875-jtrm0aj32pvaknutgnhco5kpg2b0lt5k.apps.googleusercontent.com',
    iosClientId: '346868082875-j29ohp4vireokvcnuappkvbrb8ijfrfk.apps.googleusercontent.com',
    iosBundleId: 'com.mhealth.nhap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfzHKLMBA3XEvGztkt40Jn7tT4fPJeKpU',
    appId: '1:346868082875:ios:c0682420bcc6d0b1c7e19e',
    messagingSenderId: '346868082875',
    projectId: 'mhealth-6191e',
    databaseURL: 'https://mhealth-6191e-default-rtdb.firebaseio.com',
    storageBucket: 'mhealth-6191e.appspot.com',
    androidClientId: '346868082875-jtrm0aj32pvaknutgnhco5kpg2b0lt5k.apps.googleusercontent.com',
    iosClientId: '346868082875-usafcobcv0d2sbv6pd63pg74q3l7nuej.apps.googleusercontent.com',
    iosBundleId: 'com.example.mhealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqip6Jq2lugr1KvkBQMvA1enCffUNwH-E',
    appId: '1:346868082875:web:d8d41d5c702c8807c7e19e',
    messagingSenderId: '346868082875',
    projectId: 'mhealth-6191e',
    authDomain: 'mhealth-6191e.firebaseapp.com',
    databaseURL: 'https://mhealth-6191e-default-rtdb.firebaseio.com',
    storageBucket: 'mhealth-6191e.appspot.com',
    measurementId: 'G-70YFNKXPVT',
  );
}
